
version: '2.1'

services:

  proactive:
    build: ./images/proactivems_0
    ports:
      - "8080:8080"
    restart: always
    links:
      - database
    depends_on:
      - database

  database:
    build: ./images/databasems_0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=pouet123
    restart: always